name: Welcome message Workflow

on: [push]

jobs:
  Job1-Message-Display:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Welcome to CICD"
      - run: echo "OS is ${{ runner.os }}"
      - run: ls ${{ github.workspace }}
      - run: pwd